### ISSUE TITLE
Error shows up in log when running example app on Android

### ISSUE THREAD

**Issue by BeeWarloc** [fuse-open/fuselibs#1093]
When running the standard example app (created in Fuse Studio dashboard) using `uno build android -v --run` the following error now shows up in the log:

```
InternalError: Invalid values in ArrangeMarginBox in Fuse.Controls.PageControl</Users/karsten/src/Fuse/Stuff/lib/Fuse.Elements/1.7.0-rc1-master-e7045b2/Element.Layout.uno:262>
```

This was discovered during 1.8 tools testing, and is confirmed to be a regression from 1.7. From what I can see the app is still working though, so have no idea how critical this is.

ref https://github.com/fusetools/Fuse/issues/4816

**Comment by BeeWarloc** [comment]
Marking this with "Release blocker" until we know more.

**Comment by mortoray** [comment]
A wonderful nan/inf position. Tracking down where this comes from will be a problem.

I don't think this has to be release blocker. The system can deal with this, and it's only momentary.  I'm looking nonetheless, since it shouldn't happen.

**Comment by kusma** [comment]
This was fixed a while ago.
