### ISSUE TITLE
Documentation for SafeLayout needs update

### ISSUE THREAD

**Issue by trusis666** [fuse-open/fuselibs#1132]
Reported in [forum](https://www.fusetools.com/community/forums/bug_reports/documentation_for_safelayout_seems_to_use_wrong_pr)

https://www.fusetools.com/docs/layout/safe-layout

`SafeEdgePanel` doesn't have `Edges` interface. Now we use `PadEdges`. In instructions and sample code still includes `Edges`.

**Comment by AndrewEQ** [comment]
Done: https://fuseopen.com/docs/layout/safe-layout.html
