### ISSUE TITLE
Crash in exported view when using TextInput on iOS

### ISSUE THREAD

**Issue by vvarp** [fuse-open/fuselibs#1172]
Previously discussed on forums: https://forums.fusetools.com/t/crash-in-exported-view-when-using-textinput/6862/8

Patch mentioned in discussion resolves the issue, would be good to have it merged upstream.

**Comment by kusma** [comment]
The patch mentioned is 99466284cf57677f59249819a90ab049bc7eae35, which isn't in master nor release-1.8... @nekronos, you seem to have written this... care to submit a PR?

**Comment by nekronos** [comment]
sure
