### ISSUE TITLE
Fuse.Views (Android): extending activity with FuseViewsActivity results in crash when back button is pressed

### ISSUE THREAD

**Issue by vvarp** [fuse-open/fuselibs#1177]
Mentioned couple of times on forums: 

- https://forums.fusetools.com/t/fuse-view-problems/6087
- https://forums.fusetools.com/t/exportedviews-backbutton-issue/3871

**Comment by vvarp** [comment]
This can be observed in example project posted in first of those forum posts: https://github.com/lucamtudor/hikr-fuse-view

**Comment by kusma** [comment]
[Here's a link](fusetools/premiumlibs#49) to the internal issue, just for reference.

**Comment by kusma** [comment]
Hmm, I can't really reproduce this. While I *do* get the "No RootViewport defined"-error, I don't get a crash. The app continues to work as expected for me...

**Comment by vvarp** [comment]
Let me prepare some reproduction for you - it might have something to do with the way how our Fuse app is structured

**Comment by kusma** [comment]
Actually, I think the app crashed, as I only get this error-once. My test-application doesn't have any interaction, and I suspect that it has frozen.

So, here's the stack-trace for the exception:
```
Uno.Exception: No RootViewport defined
    at Fuse.AppBase.get_CurrentRootViewport()
    at Fuse.Input.Keyboard.get_KeyTargetVisual()
    at Fuse.Input.Keyboard.RaiseKeyPressed(Uno.Platform.Key,bool,bool,bool,bool)
    at Fuse.KeyboardBootstrapper.OnKeyPressed(object,Uno.Platform.KeyEventArgs)
    at Uno.Platform.EventSources.HardwareKeys.OnKeyDown(Uno.Platform.Key,Uno.Platform.EventModifiers)
```

...And this kinda reveals that the problem is that the Uno-bootstrapping kinda assumes there's one root-window. That's obviously not the case for Fuse.Views.

But in the Fuse.Views-case, I don't think we want to handle the back-button in the first place. So, perhaps we can early out of this event in this case?

**Comment by kusma** [comment]
Here's a quick and dirty patch that seems to solve the problem for me:
```patch
commit 699f24c3e79268b13f6d5cd329a55f7b7d469758
Author: Erik Faye-Lund <erik@fusetools.com>
Date:   Tue May 22 14:58:10 2018 +0200

    Fuse.Nodes: do not handle global key-events for Fuse.Views
    
    For Fuse.Views, there's no global root-viewport that can handle
    input for us, unlike for normal apps. This means that we're just
    going to crash down these code-paths anyway.
    
    There's no reason why we need to handle keyboard-input here
    anyway. So let's just ignore the key-events.

diff --git a/Source/Fuse.Nodes/KeyboardBootstrapper.uno b/Source/Fuse.Nodes/KeyboardBootstrapper.uno
index 512c1df775..03b7943a3b 100644
--- a/Source/Fuse.Nodes/KeyboardBootstrapper.uno
+++ b/Source/Fuse.Nodes/KeyboardBootstrapper.uno
@@ -18,7 +18,10 @@ namespace Fuse
 					Focus.Move(args.IsShiftKeyPressed ? FocusNavigationDirection.Up : FocusNavigationDirection.Down);
 				}
 
-				Keyboard.RaiseKeyPressed(args.Key, args.IsMetaKeyPressed, args.IsControlKeyPressed, args.IsShiftKeyPressed, args.IsAltKeyPressed);
+				if defined(Android && Library)
+					return;
+				else
+					Keyboard.RaiseKeyPressed(args.Key, args.IsMetaKeyPressed, args.IsControlKeyPressed, args.IsShiftKeyPressed, args.IsAltKeyPressed);
 			}
 			catch (Exception e)
 			{
@@ -30,7 +33,10 @@ namespace Fuse
 		{
 			try
 			{
-				Keyboard.RaiseKeyReleased(args.Key, args.IsMetaKeyPressed, args.IsControlKeyPressed, args.IsShiftKeyPressed, args.IsAltKeyPressed);
+				if defined(Android && Library)
+					return;
+				else
+					Keyboard.RaiseKeyReleased(args.Key, args.IsMetaKeyPressed, args.IsControlKeyPressed, args.IsShiftKeyPressed, args.IsAltKeyPressed);
 			}
 			catch (Exception e)
 			{
```

Could you verify that this fixes the problem for you?

Also, does this cause similar issue on iOS? If so, the `defined(Android && Library)`-part should probably be ` defined(Mobile && Library)` instead...

**Comment by kusma** [comment]
Thinking about it a bit more, I think this might be a bit more appropriate:
```patch
diff --git a/Source/Fuse.Nodes/MobileBootstrapping.uno b/Source/Fuse.Nodes/MobileBootstrapping.uno
index 9c2b9b9fb9..987c9c78bc 100644
--- a/Source/Fuse.Nodes/MobileBootstrapping.uno
+++ b/Source/Fuse.Nodes/MobileBootstrapping.uno
@@ -17,8 +17,11 @@ namespace Fuse
 			Fuse.Platform.Lifecycle.ExitedInteractive += OnExitInteractive;
 			Fuse.Platform.Lifecycle.Terminating += OnTerminating;
 
-			Uno.Platform.EventSources.HardwareKeys.KeyDown += KeyboardBootstrapper.OnKeyPressed;
-			Uno.Platform.EventSources.HardwareKeys.KeyUp += KeyboardBootstrapper.OnKeyReleased;
+			if (Mobile && Library)
+			{
+				Uno.Platform.EventSources.HardwareKeys.KeyDown += KeyboardBootstrapper.OnKeyPressed;
+				Uno.Platform.EventSources.HardwareKeys.KeyUp += KeyboardBootstrapper.OnKeyReleased;
+			}
 		}
 
 		static void OnTerminating(Fuse.Platform.ApplicationState state)
```
@nekronos: What do you think? Why would we want the keyboard bootstrapping with Fuse.Views in the first place?

**Comment by vvarp** [comment]
I took the similar approach, by capturing back key in Android activity in `onKeyDown` and `onKeyUp`, but yeah, it's better to do that in Uno.

However, it would be still useful to properly handle back button between Fuse and host app - in our case Fuse view is app-like experience, where being able to navigate through using platform-native ways makes perfect sense.

**Comment by kusma** [comment]
@nekronos: Uh, yes. I obviously didn't test this! 🤣

@vvarp: The problem for now, is that the Fuse Views don't get input events routed through the UI tree, like they should. And I sadly don't think correcting this is a quick-fix... :/

It would be great to see someone tackle this, but I don't think I'm the right person right now. IMO it should be use-case driven rather than me making guesses at what people *really* want to do ;)

**Comment by kusma** [comment]
Since the bootstrapping is just going to crash ATM, I'll include a version of this patch for 1.9 (but actually *tested* this time).

We can have a look at dealing with the back-key later :)
