### ISSUE TITLE
Push not working properly 

### ISSUE THREAD

**Issue by ckarmy** [fuse-open/fuselibs#1179]
When I receive a push notification on Android and my app is open I receive the push on push.on(“receivedMessage”, function(payload)…

But when my app is on background or closed I dont receive the push in my notification bar! This work fine in previous versions! Now in 1.8.2 is broken!

How can I fix this?

Tested on Android 8.0

**Comment by ckarmy** [comment]
Maybe is this: https://stackoverflow.com/questions/43093260/notification-not-showing-in-oreo

How can implement it?

**Comment by cbaggers** [comment]
Was this the first time you have tested on android 8? If the only change that caused the issue is 1.8.2 then we should start with the assumption that that is the problem.

**Comment by ckarmy** [comment]
The problem start when I set
`"SDK": {
      "BuildToolsVersion": "23.0.1",
      "CompileVersion": 23,
      "MinVersion": 16,
      "TargetVersion": 26
    }`
I need to set this because from August 2018 the minimium TargetVersion would be the 26 (https://github.com/fusetools/fuse-releases/issues/1#issuecomment-390462236)

**Comment by cbaggers** [comment]
Oh interesting! Looks like I have some pain in my future then :D

A quick skim of that nice stackoverflow answer suggests the change needs to be in the notification builder, which you can find here https://github.com/fuse-compound/Fuse.Firebase/blob/ede5fa58fdc989e35ee5d2e201c00253093393b9/src/Firebase.Notifications.Android/Android/PushNotificationReceiver.java#L200

I also this this may be the end of the line for `Fuse.Notifications` android as GCM is heavily deprecated.

**Comment by kusma** [comment]
Hmm, does this ticket belong in the Fuse.Firebase repo instead of here?

**Comment by devadiab** [comment]
@ckarmy, i have big experience in this field
try to use Fuse.PushNotifications for `Android` not to use fuse-compound/Fuse.Firebase.

**Its fully functioning and stable.**

Also if you need to use `Firebase` for `iOS` you can use it and to combine both (Fuse.Push for `Android` and Fuse.Firebase.Notifications.. for `iOS`) for registration id and 
`push.on(“receivedMessage”, function(payload)…` the one from `Fuse.Push..` will catch both cases from `Android` and `iOS`.

I'm using this method on my projects.

**Comment by jhsware** [comment]
@ckarmy Shouldn't this issue be closed?
