### ISSUE TITLE
V8Simple source code

### ISSUE THREAD

**Issue by mortend** [fuse-open/fuselibs#1191]
This isn't an issue with this repository per se, but...

I'm looking for the V8Simple source code, for custom building and experimentation.

Currently, I can find the prebuilt V8Simple binaries here: https://github.com/fuse-open/fuselibs/tree/master/Source/Fuse.Scripting.JavaScript/V8/lib

Thanks!

**Comment by kusma** [comment]
@mortend: good point! I'll have a look!

**Comment by kusma** [comment]
@ollef: Fixing this would have to include publishing the code that's in [this repo](https://github.com/fusetools/V8.Simple). Do you know about a technical reason not to do that? If not, I'll have a look at the legal stuff (get formal approval etc) tomorrow...

**Comment by ollef** [comment]
Ah yes, that should be opened too! Go for it! :smile:

**Comment by kusma** [comment]
@mortend: Here you go: https://github.com/fuse-open/V8.Simple

**Comment by mortend** [comment]
@kusma: Nice, thanks!
