### ISSUE TITLE
Multiple dex support

### ISSUE THREAD

**Issue by Dhvl-Golakiya** [fuse-open/fuselibs#1201]
Hi,

I am integrating Mapbox and FIrebase with Fusetools. And I need support for MultiDex. Does it is in your queue?

**Comment by kusma** [comment]
I don't know of anyone working on this.

**Comment by poul-kg** [comment]
We need multidex as it prevents us from integrating 3rd party modules in Android. Is that possible if we can add it ourselves? We never modified core, but we have experience adding 3rd party modules, and some uno experience. We stuck right now.

We need to add branch.io support, it requires multidex support.
While mapbox works without multidex, some mapbox plugins require multidex and we can't use them, and we're hacking with mapbox as much as we can.

**Comment by kusma** [comment]
Sure, it should be possible to add this yourselves. You probably want to look at the [Uno repo](https://github.com/fuse-open/uno), in particular [here](https://github.com/fuse-open/uno/blob/0c837eb34d04e662ece43cf8f0d605ff273e819f/Library/Core/UnoCore/Targets/Android/app/build.gradle#L74).

**Comment by ichan-mb** [comment]
Multidex has been added for quite some time, it is part of this PR: https://github.com/fuse-open/uno/pull/254
