### ISSUE TITLE
Error Building Android App (Error with Google Play Services Maps)

### ISSUE THREAD

**Issue by TChong** [fuse-open/fuselibs#1216]
I'm having trouble build an Android version of my app after the latest PR.

When I try to run a build to get the latest PRs, I get this error:

* What went wrong:
>A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.google.android.gms:play-services-maps:12.0.1.
     Required by:
         Preview:app:unspecified

Phone Details:
Samsung Galaxy S5
Android 6.0.1.

**Comment by ichan-mb** [comment]
this issue has been fixed
