### ISSUE TITLE
XCode: "Error while reading JPEG file: Application transferred too few scanlines"

### ISSUE THREAD

**Issue by Nicero** [fuse-open/fuselibs#1272]
When building a iOS release version choosing _Export for iOS_ the following basic code will make XCode return "Error while reading JPEG file: Application transferred too few scanlines":

    cameraRoll.getImage().then(function(image) {
        selectedImage.value = image;
    }, function(error) {
        console.log(error);
    });
and no image is shown. The above code will work fine in _Preview for iOS_ and in Android (preview and export)

**Comment by kusma** [comment]
I suspect that the error depends on what's in the camera-roll of your device.

**Comment by Nicero** [comment]
Thank you for writing back. The images in camera-roll are pictures I'm taking with the iPhone camera, `image` does contain it's information (`path`, `name`, `height `and `width`). The issue is that `selectedImage.value` remains empty. 
After dozens of tests it seems that iOS needs `selectedImage.value = image.path`, where Android works fine simply with `selectedImage.value =image`. But as reported is Fusetools [forum ](https://forums.fusetools.com/t/some-pictures-from-camera-roll-wont-upload/5650) while back ago this error seems to happen sometimes!

**Comment by Nicero** [comment]
Seem to have found a workaround. Resize the image before displaying it:

    cameraRoll.getImage().then(function(image) {
        
        // As soon as you choose the image from the gallery resize it
        var args = { desiredWidth: 800, desiredHeight: 800, mode:ImageTools.KEEP_ASPECT };
        return ImageTools.resize(image, args);

    }).then(same => {
        
        // then show the resized image (here is saved in 'same')
        selectedImage.value = same.path;
        
        // And if you want to convert the resized image to base64...
        ImageTools.getBase64FromImage(same).then(function(base64Image) { 
            console.log("The base64 encoded image is: " + base64Image); 
        });

    }, function(error) {
        console.log(error);
    })

In Android (preview or export) the image is correctly displayed directly from the gallery so this may not be necessary, but resizing the image before displaying it even in Android may be a good idea too.
