### ISSUE TITLE
Normal ImageFill doesn't load image

### ISSUE THREAD

**Issue by AndrewEQ** [fuse-open/fuselibs#1276]
@ichan-mb, @kusma 

**Describe the bug**
My image from the web was not loading, just says that it couldn't load the .jpg.

**To Reproduce**

```
<ImageFill StretchMode="UniformToFill" WrapMode="ClampToEdge" MemoryPolicy="UnloadUnused">
  <MultiDensityImageSource>
    <HttpImageSource Density="1" Url="{image1}" />
    <HttpImageSource Density="2" Url="{image2}" />
    <HttpImageSource Density="3" Url="{image3}" />
  </MultiDensityImageSource>
</ImageFill>
```

**Expected behavior**
Image loads and displays

**Smartphone (please complete the following information):**
 - Device: iPhoneSE
 - OS: 12.3

**Additional context**
When I rollback the disk cache commits, the images load and display correctly.

**Comment by ichan-mb** [comment]
try to investigate today

**Comment by ichan-mb** [comment]
I have found the issue, fix is on the way.
