### ISSUE TITLE
Unable to restrict orientation to portrait

### ISSUE THREAD

**Issue by AndrewEQ** [fuse-open/fuselibs#1374]
Hi guys,

There's a property that deals with the restriction of the orientation of the app:

https://fuseopen.com/docs/basics/uno-projects.html#mobile-orientations

When set to "Portrait", it doesn't limit the app to portrait anymore on iOS.

I believe its to do with the recently merged change:
https://github.com/fuse-open/fuselibs/pull/1354

I think if a developer restricts their app to a specific orientation, then they are unlikely to want to define every pages orientation.

So the feature should probably only be enabled when the `Mobile.Orientations` setting is set to Auto (which is the Mobile.Orientations default).

Or if the dev sets the Mobile.Orientations to `Landscape` for instance, that they could only choose between "LandscapeLeft" and "LandscapeRight" when setting their pages orientation, so the orientation feature could still exist all the time, just that it needs to take into account the `Mobile.Orientations` setting.

**Comment by ichan-mb** [comment]
Thanks for reporting, I'll try to investigate it.
