### ISSUE TITLE
Fuse.Launcher make not compatible to all only WIFI tablets 

### ISSUE THREAD

**Issue by ckarmy** [fuse-open/fuselibs#1416]
Fuse.Launcher add `<uses-permission android:name="android.permission.CALL_PHONE" />` to the manifest and make not compatible to all only WIFI tablets. To solve this and make compatible all tablets we need to add to the manifest: 
`<uses-feature android:name="android.hardware.telephony" android:required="false"/>`.

I make a `.UXL` file to replace the manifest.
Any chance to add this by default? Or maybe to add via `.unoproj`?

Thanks!

**Comment by ckarmy** [comment]
I'm not sure if `CALL_PHONE` is added because `Fuse.Launcher` or is added always

**Comment by ichan-mb** [comment]
> Any chance to add this by default? Or maybe to add via .unoproj?

You can configure it in the unoproj file. just add:
```
{
    "Android": {
        "UsesFeatures": {
             "AndroidHardwareTelephony": false
        }
    }
}
```

**Comment by ckarmy** [comment]
Thanks!!! Problem solved! How can I read more about the unoproj capabilities?
