### ISSUE TITLE
Read-only TextView can be selected and edited on Android

### ISSUE THREAD

**Issue by eksperts** [fuse-open/fuselibs#492]
[Reported on community](https://www.fusetools.com/community/forums/general/selectable_text).

Repro:
```
<App>
  <StackPanel>
    <TextView IsReadOnly="true" Margin="30" FontSize="16" TextWrapping="Wrap" Value="I'm a really long text and I need to be selected and copied! I'm a really long text and I need to be selected and copied! I'm a really long text and I need to be selected and copied! I'm a really long text and I need to be selected and copied!" />
  </StackPanel>
</App>
```
One can click on the `TextView`, it gets focus and on-screen keyboard gets shown. The content then can be edited. It is expected that this would not happen.

**Comment by fusebuild** [comment]
The forum thread [Selectable text](https://www.fusetools.com/community/forums/general/selectable_text) posted by Ana Almeida was linked to this issue.

**Comment by trusis666** [comment]
Still got issue with `IsReadOnly`. Reported in [forum](https://www.fusetools.com/community/forums/bug_reports/isreadonly_attribute_in_textinput_is_ignored).
