### ISSUE TITLE
Models: Add support for ES6 class fields (through a babel plugin)

### ISSUE THREAD

**Issue by Duckers** [fuse-open/fuselibs#726]
The default es2015 implementation does not support class fields, but most transpiler environments are configured to support it anyway. So instead of 

```JS
class Foo {
     constructor() { this.bar = 1 }
}
```

we can simply write

```JS
class Foo {
    bar = 1
}
```

I've done some googling but not been able to determine what is the most kosher plugin to use.

**Comment by sebbert** [comment]
This feature is still in proposal stage 3, and not yet part of any ECMAScript standard. Therefore, I'm reluctant to include it - as we can introduce this later on without breaking user code, but not the other way around.

> most transpiler environments are configured to support it anyway
Do you have statistics that support this claim?
