### ISSUE TITLE
Default fonts look quite different on iOS >=11

### ISSUE THREAD

**Issue by ianychoi** [fuse-open/fuselibs#876]
Version: 1.5.0 (build 15042)

- iOS 11.2 (iPhone 7 Plus, SImulator)
<img width="280" alt="screen shot 2017-12-18 at 12 31 18 pm" src="https://user-images.githubusercontent.com/6965982/34090196-8e2411f8-e3f8-11e7-9679-0f860efe2832.png">

- iOS 10.3.1 (iPhone 7 Plus, Simulator)
<img width="299" alt="screen shot 2017-12-18 at 1 25 17 pm" src="https://user-images.githubusercontent.com/6965982/34090184-7dd417a8-e3f8-11e7-9d43-87dacdd79754.png">

- Local preview
![screen shot 2017-12-18 at 11 28 27 am](https://user-images.githubusercontent.com/6965982/34090206-a89147b8-e3f8-11e7-99b3-68c5a4b38e0c.png)

- iPhone X (11.2, Simulator)
![screen shot 2017-12-18 at 11 26 31 am](https://user-images.githubusercontent.com/6965982/34090216-b7155bf8-e3f8-11e7-9d5b-2e360cfba778.png)
![screen shot 2017-12-18 at 11 26 24 am](https://user-images.githubusercontent.com/6965982/34090217-b74e9422-e3f8-11e7-9e7f-8a3d2f4d357c.png)
![screen shot 2017-12-18 at 11 26 01 am](https://user-images.githubusercontent.com/6965982/34090218-b78d352e-e3f8-11e7-8950-e22800b6d0f6.png)

**Comment by kusma** [comment]
Ugh, what has Apple done this time? :(

**Comment by kusma** [comment]
Hmm, I can't reproduce this with ManualTestingApp (the Default Font test there) on iOS 11.2 in the iPhoneX simulator. The font looks fine there...

**Comment by kusma** [comment]
This is what I get with iPhoneX 11.2:
<img width="517" alt="screen shot 2017-12-18 at 10 19 30" src="https://user-images.githubusercontent.com/47073/34098557-0b55ca70-e3dd-11e7-9cc7-57b82d6eccf1.png">

**Comment by kusma** [comment]
The above is using fuselibs master, by the way.
I get the same result, except that the app doesn't fill the whole screen, if I use release-1.4. So I'm not really sure what's going on for you @ianychoi, but it seems this is not a fundamental problem with our software. Perhaps you should try to reinstall the iOS11 image, or make sure you have an up-to-date XCode installation?

**Comment by ichan-mb** [comment]
this is already fixed: https://github.com/fuse-open/fuselibs/pull/1291
