### ISSUE TITLE
TimePicker crashes on iOS with EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by eksperts** [fuse-open/fuselibs#883]
[Reported on community](https://www.fusetools.com/community/forums/bug_reports/timepicker_crashes_xcode)

When I am using the example in TimePicker Class (after correcting the Is24HourTimeView) and running it on preview in xcode it crashes with an EXC_BAD_ACCESS when I dial in the time. Have tried with both Fuse 1.4 and 1.5. Running Xcode 9.2.

Asked for a repro on the forum thread.

**Comment by fusebuild** [comment]
The forum thread [TimePicker crashes xcode](https://www.fusetools.com/community/forums/bug_reports/timepicker_crashes_xcode) posted by Morten was linked to this issue.
