### ISSUE TITLE
Bad color code breaks compilation

### ISSUE THREAD

**Issue by mortoray** [fuse-open/fuselibs#949]
A user entered `Color="#36"` which causes UX compilation to break, and Preview to fail to show anything.

It's clearly a user-error, but the abrupt break in Preview caused them distress -- they had no idea what was wrong as they were making minor changes and suddenly everything went away.

This issue might be more of a problem of interplay between UX compiler and Preview in cases of broken code. It's not clear exactly what should happen.

**Comment by AndrewEQ** [comment]
If not a valid color code, color should not be attempted to be changed and error message with reason should be displayed.

**Comment by ichan-mb** [comment]
works on Fuse X
