### ISSUE TITLE
CameraRoll permission issue when sellecting an image

### ISSUE THREAD

**Issue by trusis** [fuse-open/fuselibs#983]
[Reported on forum](https://www.fusetools.com/community/forums/bug_reports/cameraroll_permission_issue_when_sellecting_an_ima)

MacOS Siera High
Fusetools 1.5 (build 150046)
Reproduced: iPhone X, iPhone 7, iPhone SE, iPhone 6
Not affected: Nexus 5 Android 6.0.1

We're having an issue with the permissions for the cameraroll. When selecting a image, permission is asked after selecting image and this clears the selected image. Therefore to select a image first time users have to take the same steps twice.

Is this a bug in Fuse or is there some kind of work around this issue?

Video: To make things clear: https://youtu.be/nwrvvy3HTJ0

# Expected behavior:
 Permission should be asked, before accessing images on a device. After that, I can select an image. 

# Minimal code to reproduce:
```
<App>

    <JavaScript>

        var cameraRoll = require("FuseJS/CameraRoll");
        var Observable = require("FuseJS/Observable");

        var TheImage = Observable();


        module.exports = {
            TheImage:TheImage,
            SetImage : function() {

                cameraRoll.getImage()
                .then(function(image) {
                    TheImage.value = image;
                }, function(error) {
                });
            }
        }    

    </JavaScript>
    <Button Text="test" Clicked="{SetImage}" />
    <Image File="{TheImage}"/>
</App>
```
When ruuning `fuse build --target=iOS -adebug` in Xcode I get this error:
```
[discovery] errors encountered while discovering extensions: Error Domain=PlugInKit Code=13 "query cancelled" UserInfo={NSLocalizedDescription=query cancelled}
```

**Comment by fusebuild** [comment]
The forum thread [Cameraroll permission issue when sellecting an image](https://www.fusetools.com/community/forums/bug_reports/cameraroll_permission_issue_when_sellecting_an_ima) posted by Ruud_ was linked to this issue.

**Comment by trusis666** [comment]
Related problem form [forum](https://www.fusetools.com/community/forums/bug_reports/cameraroll_-_first_time_use_bug?page=1&highlight=f1e0bb2c-de8d-4b56-91e7-170377465135#post-f1e0bb2c-de8d-4b56-91e7-170377465135)

**Comment by fusebuild** [comment]
The forum thread [CameraRoll tries to get image before asking ](https://www.fusetools.com/community/forums/bug_reports/cameraroll_tries_to_get_image_before_asking) posted by Luis Rodriguez was linked to this issue.

**Comment by fusebuild** [comment]
The forum thread [CameraRoll - First time use bug](https://www.fusetools.com/community/forums/bug_reports/cameraroll_-_first_time_use_bug) posted by Andrew was linked to this issue.

**Comment by fusebuild** [comment]
The forum thread [Can't get images from gallery through Fuse.CameraRoll on iOS](https://www.fusetools.com/community/forums/general/cant_get_images_from_gallery_through_fusecamerarol) posted by Ivan Onishchenko was linked to this issue.

**Comment by cbaggers** [comment]
Looking at this today
